# Предложения
## Получить список предложений
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Cool apartment for couples",
  "description": "Comfortable private room near a large city park, perfect for short and long stays",
  "city": "Paris",
  "previewImage": "https://my-mock.com/preview-image-10.jpg",
  "housingImages": [
    "https://my-mock.com/housing-image-10.jpg",
    "https://my-mock.com/housing-image-11.jpg",
    "https://my-mock.com/housing-image-12.jpg",
    "https://my-mock.com/housing-image-13.jpg",
    "https://my-mock.com/housing-image-14.jpg",
    "https://my-mock.com/housing-image-15.jpg"
  ],
  "isPremium": false,
  "isFavorite": false,
  "housingType": "apartment",
  "roomsCount": 2,
  "guestsCount": 4,
  "price": 34050,
  "amenities": [
    "Breakfast",
    "Laptop friendly workspace",
    "Washer"
  ],
  "authorId": "69baa78682093da034c576d2",
  "coordinates": {
    "latitude": 40.3235,
    "longitude": 60.3582
  }
}

###
